/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(1200, 800);
        setTitle("HỆ THỐNG QUẢN LÝ TRƯỜNG MẦM NON!!!");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnDoiMatKhau = new javax.swing.JMenuItem();
        mnDangXuat = new javax.swing.JMenuItem();
        mnQuanLyNienKhoa = new javax.swing.JMenu();
        mnQLNienKhoa = new javax.swing.JMenuItem();
        mnQuanLyLop = new javax.swing.JMenuItem();
        mnQuanLyHocSinh = new javax.swing.JMenuItem();
        mnQuanLyGiaoVien = new javax.swing.JMenuItem();
        mnQuanLyThucDon = new javax.swing.JMenuItem();

        menu3.setLabel("File");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\User-info.48.png")); // NOI18N
        jMenu1.setText("Tài khoản");

        mnDoiMatKhau.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\changePass.24.png")); // NOI18N
        mnDoiMatKhau.setText("Đổi mật khẩu");
        mnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mnDoiMatKhau);

        mnDangXuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\logout.24.png")); // NOI18N
        mnDangXuat.setText("Đăng Xuất");
        mnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnDangXuat);

        jMenuBar1.add(jMenu1);

        mnQuanLyNienKhoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\management.48.png")); // NOI18N
        mnQuanLyNienKhoa.setText("Quản lý chức năng");

        mnQLNienKhoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Mono-School.24.png")); // NOI18N
        mnQLNienKhoa.setText("Quản lý niên khóa");
        mnQLNienKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQLNienKhoaActionPerformed(evt);
            }
        });
        mnQuanLyNienKhoa.add(mnQLNienKhoa);

        mnQuanLyLop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Classroom.24.png")); // NOI18N
        mnQuanLyLop.setText("Quản lý lớp");
        mnQuanLyLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuanLyLopActionPerformed(evt);
            }
        });
        mnQuanLyNienKhoa.add(mnQuanLyLop);

        mnQuanLyHocSinh.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Students24.png")); // NOI18N
        mnQuanLyHocSinh.setText("Quản lý học sinh");
        mnQuanLyHocSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuanLyHocSinhActionPerformed(evt);
            }
        });
        mnQuanLyNienKhoa.add(mnQuanLyHocSinh);

        mnQuanLyGiaoVien.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Teacher-female24.png")); // NOI18N
        mnQuanLyGiaoVien.setText("Quản lý giáo viên");
        mnQuanLyGiaoVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuanLyGiaoVienActionPerformed(evt);
            }
        });
        mnQuanLyNienKhoa.add(mnQuanLyGiaoVien);

        mnQuanLyThucDon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Menu.24.png")); // NOI18N
        mnQuanLyThucDon.setText("Quản lý thực đơn");
        mnQuanLyThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQuanLyThucDonActionPerformed(evt);
            }
        });
        mnQuanLyNienKhoa.add(mnQuanLyThucDon);

        jMenuBar1.add(mnQuanLyNienKhoa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1018, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu3ActionPerformed

    private void mnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDangXuatActionPerformed
        new DangXuat().setVisible(true);
    }//GEN-LAST:event_mnDangXuatActionPerformed

    private void mnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoiMatKhauActionPerformed
        new DoiMatKhau().setVisible(true);
    }//GEN-LAST:event_mnDoiMatKhauActionPerformed

    private void mnQLNienKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQLNienKhoaActionPerformed
        new QL_NienKhoa().setVisible(true);
    }//GEN-LAST:event_mnQLNienKhoaActionPerformed

    private void mnQuanLyLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuanLyLopActionPerformed
        new QL_Lop().setVisible(true);
    }//GEN-LAST:event_mnQuanLyLopActionPerformed

    private void mnQuanLyHocSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuanLyHocSinhActionPerformed
        new QL_HocSinh().setVisible(true);
    }//GEN-LAST:event_mnQuanLyHocSinhActionPerformed

    private void mnQuanLyGiaoVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuanLyGiaoVienActionPerformed
        new QL_GiaoVien().setVisible(true);
    }//GEN-LAST:event_mnQuanLyGiaoVienActionPerformed

    private void mnQuanLyThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQuanLyThucDonActionPerformed
        new QL_ThucDon().setVisible(true);
    }//GEN-LAST:event_mnQuanLyThucDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JMenuItem mnDangXuat;
    private javax.swing.JMenuItem mnDoiMatKhau;
    private javax.swing.JMenuItem mnQLNienKhoa;
    private javax.swing.JMenuItem mnQuanLyGiaoVien;
    private javax.swing.JMenuItem mnQuanLyHocSinh;
    private javax.swing.JMenuItem mnQuanLyLop;
    private javax.swing.JMenu mnQuanLyNienKhoa;
    private javax.swing.JMenuItem mnQuanLyThucDon;
    // End of variables declaration//GEN-END:variables
}
