/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.Controller_NguoiDung;
import controller.Validation;
import java.awt.Color;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import models.BienToanCuc;
import models.NguoiDung;
public class JF_ThongTinPhuHuynh extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinPhuHuynh
     */
    ArrayList<NguoiDung> listPH;
    public JF_ThongTinPhuHuynh() {
        initComponents();
        setLocationRelativeTo(null);
        lamMoi();
        txt_MaPH.setEnabled(false);
        txt_TenDN.setEnabled(false);
        //Lấy list Phụ huynh từ CSDL
        listPH = new Controller_NguoiDung().getListNguoiDung();
        btn_Nam.setSelected(true);
        btn_PHMoi.setSelected(true);
        
        int id = 1;
        boolean state;
        while(true){
            state = false;
            for(NguoiDung ph: listPH){
                if(ph.getMaND().equals("ph"+id)){
                    state = true;
                    break;
                }
            }
            if(!state) break;
            ++id;
        }
        txt_MaPH.setText("ph"+ id);
        txt_TenDN.setText(txt_MaPH.getText());
        
        //Load lại thông tin PH vừa điền khi chưa thực hiện nhấn Thêm hoặc Cập Nhật
        //Cho vào try-catch do TH btc null --> Exception
        try{
            HienThiThongTinPH(new BienToanCuc());
        }catch(Exception e) {
            e.printStackTrace();
        }
        btn_OK.setEnabled(false);
        lbl_ValidEmail.setText(null); //nếu k gán thì ban đầu không phải null --> không hiển thị được OK khi t cho phép giá trị này null ở database
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //Hàm load lại Thông tin PH lên biểu mẫu
    public void HienThiThongTinPH(BienToanCuc btc){
        NguoiDung ph = btc.phuhuynh;
        
        if(btc.luaChonPH == 1){
            btn_PHMoi.setSelected(true);
            txt_MaPH.setText(ph.getMaND());
            txt_TenDN.setText(ph.getTenDN());
            txt_HoTen.setText(ph.getHoTen());
            txt_NamSinh.setText(ph.getNamSinh()+"");

            if(ph.isGioiTinh()){
                btn_Nam.setSelected(true);
            } else {
                btn_Nu.setSelected(true);
            }

            txt_DanToc.setText(ph.getDanToc());
            txt_CCCD.setText(ph.getCccd());
            txt_DiaChi.setText(ph.getDiaChi());
            txt_SDT.setText(ph.getSoDT());
            txt_Email.setText(ph.getEmail());
            
            //Label validation --> cho bằng null khi ban đầu chọn 1 học sinh --> có sẵn thông tin PH
            lbl_ValidCCCD.setText(null);
            lbl_ValidDanToc.setText(null);
            lbl_ValidDiaChi.setText(null);
            lbl_ValidEmail.setText(null);
            lbl_ValidHoTen.setText(null);
            lbl_ValidMaPH.setText(null);
            lbl_ValidNamSinh.setText(null);
            lbl_ValidSDT.setText(null);
            
        } else if(btc.luaChonPH==2){
            btn_PHCu.setSelected(true);
            
            txt_MaPHCu.setText(btc.maND);
        }
         
    }
    public void lamMoi(){
        lbl_ValidCCCD.setText("(*)");
        txt_CCCD.setBackground(Color.white);
        lbl_ValidDanToc.setText("(*)");
        txt_DanToc.setBackground(Color.white);
        lbl_ValidDiaChi.setText("(*)");
        txt_DiaChi.setBackground(Color.white);
//        lbl_ValidEmail.setText("(*)");
        txt_Email.setBackground(Color.white);
        lbl_ValidHoTen.setText("(*)");
        txt_HoTen.setBackground(Color.white);
        lbl_ValidMaPH.setText("(*)");
        txt_MaPHCu.setBackground(Color.white);
        lbl_ValidNamSinh.setText("(*)");
        txt_NamSinh.setBackground(Color.white);
        lbl_ValidSDT.setText("(*)");
        txt_SDT.setBackground(Color.white);
        
        txt_HoTen.setText("");
        txt_NamSinh.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        txt_DanToc.setText("");
        txt_CCCD.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        txt_Email.setText("");
        txt_MaPHCu.setText("");
        
        btn_Nam.setSelected(true);
        btn_PHMoi.setSelected(true);
        txt_MaPHCu.setEnabled(false);
    }
    //Hàm lựa chọn PH: Chọn PH mới thì clear PH cũ mà chọn PH cũ thì clear PH mới
    public void luaChonPH(){
        if(btn_PHCu.isSelected()){
            lamMoi();
            btn_PHCu.setSelected(true);
            txt_CCCD.setEnabled(false);
            txt_DanToc.setEnabled(false);
            txt_DiaChi.setEnabled(false);       
            txt_HoTen.setEnabled(false);
            txt_NamSinh.setEnabled(false);
            txt_SDT.setEnabled(false);
            txt_Email.setEnabled(false);
            btn_Nam.setEnabled(false);
            btn_Nu.setEnabled(false);
            txt_MaPHCu.setEnabled(true);
        }
        if(btn_PHMoi.isSelected()){
            lamMoi();
            btn_PHMoi.setSelected(true);
            txt_CCCD.setEnabled(true);
            txt_DanToc.setEnabled(true);
            txt_DiaChi.setEnabled(true);       
            txt_HoTen.setEnabled(true);
            txt_NamSinh.setEnabled(true);
            txt_SDT.setEnabled(true);
            txt_Email.setEnabled(true);
            btn_Nam.setEnabled(true);
            btn_Nu.setEnabled(true);
            txt_MaPHCu.setEnabled(false);
        }
    }
    //Hàm set Enable OK
    public boolean checkValidation(){
        if(btn_PHMoi.isSelected()){
            if(lbl_ValidCCCD.getText()==null&&lbl_ValidHoTen.getText()==null&&lbl_ValidNamSinh.getText()==null&&
                    lbl_ValidDanToc.getText()==null&&lbl_ValidDiaChi.getText()==null&&lbl_ValidSDT.getText()==null&&
                    lbl_ValidEmail.getText()==null){
                return true;
            } else{
                return false;
            }
        } else {
            if(btn_PHCu.isSelected()){
                if(lbl_ValidMaPH.getText()==null){
                    return true;
                } else{
                    return false;
                }
            }
        
        }
        return false;
    }
    //Kiểm tra mã PH là của PH mứi hay PH đã tồn tại
    public boolean kiemTraTonTaiPH(){
        for(NguoiDung ph: listPH){
            if(ph.getMaND().equals(txt_MaPH.getText())){
                return  true;
            }
        }
        return false;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        abc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_NamSinh = new javax.swing.JTextField();
        txt_DanToc = new javax.swing.JTextField();
        txt_CCCD = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        btn_OK = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Nam = new javax.swing.JRadioButton();
        btn_Nu = new javax.swing.JRadioButton();
        btnDong = new javax.swing.JButton();
        btn_PHMoi = new javax.swing.JRadioButton();
        btn_PHCu = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txt_MaPHCu = new javax.swing.JTextField();
        txt_MaPH = new javax.swing.JTextField();
        txt_TenDN = new javax.swing.JTextField();
        lbl_ValidHoTen = new javax.swing.JLabel();
        lbl_ValidNamSinh = new javax.swing.JLabel();
        lbl_ValidDanToc = new javax.swing.JLabel();
        lbl_ValidCCCD = new javax.swing.JLabel();
        lbl_ValidDiaChi = new javax.swing.JLabel();
        lbl_ValidSDT = new javax.swing.JLabel();
        lbl_ValidEmail = new javax.swing.JLabel();
        lbl_ValidMaPH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Phụ Huynh");

        abc.setText("Mã phụ huynh:");

        jLabel3.setText("Tên đăng nhập: ");

        jLabel4.setText("Mật khẩu: Khởi tạo ban đầu mặc định giống mã phụ huynh");

        jLabel6.setText("Họ tên");

        txt_HoTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_HoTenKeyReleased(evt);
            }
        });

        jLabel7.setText("Năm sinh");

        jLabel8.setText("Giới tính");

        jLabel9.setText("Dân tộc");

        jLabel10.setText("CCCD");

        jLabel11.setText("Đạ chỉ");

        jLabel12.setText("Số điện thoại");

        jLabel13.setText("Email");

        txt_NamSinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NamSinhKeyReleased(evt);
            }
        });

        txt_DanToc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DanTocKeyReleased(evt);
            }
        });

        txt_CCCD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CCCDKeyReleased(evt);
            }
        });

        txt_DiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DiaChiKeyReleased(evt);
            }
        });

        txt_SDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_SDTKeyReleased(evt);
            }
        });

        txt_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_EmailKeyReleased(evt);
            }
        });

        btn_OK.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Ok24.png")); // NOI18N
        btn_OK.setText("OK");
        btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OKActionPerformed(evt);
            }
        });

        btn_LamMoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Refresh.png")); // NOI18N
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_Nam);
        btn_Nam.setText("Nam");

        buttonGroup1.add(btn_Nu);
        btn_Nu.setText("Nữ");

        btnDong.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\CloseJF24.png")); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        buttonGroup2.add(btn_PHMoi);
        btn_PHMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_PHMoi.setText("Phụ huynh mới");
        btn_PHMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PHMoiActionPerformed(evt);
            }
        });

        buttonGroup2.add(btn_PHCu);
        btn_PHCu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_PHCu.setText("Phụ huynh cũ");
        btn_PHCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PHCuActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã phụ huynh");

        txt_MaPHCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_MaPHCuKeyReleased(evt);
            }
        });

        lbl_ValidHoTen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidHoTen.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ValidHoTen.setText("(*)");
        lbl_ValidHoTen.setToolTipText("");

        lbl_ValidNamSinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidNamSinh.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ValidNamSinh.setText("(*)");

        lbl_ValidDanToc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidDanToc.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ValidDanToc.setText("(*)");

        lbl_ValidCCCD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidCCCD.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ValidCCCD.setText("(*)");

        lbl_ValidDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidDiaChi.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ValidDiaChi.setText("(*)");

        lbl_ValidSDT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidSDT.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ValidSDT.setText("(*)");

        lbl_ValidEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidEmail.setForeground(new java.awt.Color(204, 0, 0));

        lbl_ValidMaPH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ValidMaPH.setForeground(new java.awt.Color(204, 0, 0));
        lbl_ValidMaPH.setText("(*)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_NamSinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(txt_HoTen, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ValidHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_ValidNamSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_DanToc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ValidDanToc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ValidCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ValidDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ValidSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_ValidEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDong)
                        .addGap(18, 18, 18)
                        .addComponent(btn_LamMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btn_OK)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_MaPHCu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ValidMaPH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_PHMoi)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(abc))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_TenDN, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txt_MaPH)))
                            .addComponent(btn_PHCu))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_PHMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_TenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ValidHoTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ValidNamSinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btn_Nam)
                    .addComponent(btn_Nu))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_DanToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_ValidDanToc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_ValidCCCD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_ValidDiaChi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ValidSDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ValidEmail))
                .addGap(18, 18, 18)
                .addComponent(btn_PHCu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaPHCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ValidMaPH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_OK)
                    .addComponent(btn_LamMoi)
                    .addComponent(btnDong))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OKActionPerformed
        if(btn_PHMoi.isSelected()){
            
            NguoiDung ph = new NguoiDung();
        try{
            ph.setMaND(txt_MaPH.getText());
            ph.setHoTen(txt_HoTen.getText());
            ph.setDanToc(txt_DanToc.getText());
            ph.setTenDN(txt_MaPH.getText());
            ph.setCccd(txt_CCCD.getText());
            ph.setDiaChi(txt_DiaChi.getText());
            ph.setSoDT(txt_SDT.getText());
            ph.setEmail(txt_Email.getText());
            ph.setMatKhau(txt_MaPH.getText());

             //set giới tính
            if(btn_Nam.isSelected()){
               ph.setGioiTinh(true);
            } else if(btn_Nu.isSelected()){
                ph.setGioiTinh(false);
            }

            ph.setNamSinh(Integer.parseInt(txt_NamSinh.getText()));
            ph.setVaiTro("phuhuynh");
            
            BienToanCuc btc = new BienToanCuc();
            btc.phuhuynh = ph;
            btc.luaChonPH =1;
            
            this.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu trống hoặc không đúng định dạng, vui lòng kiểm tra lại!");
            }
        } else if(btn_PHCu.isSelected()){
            
            BienToanCuc btc = new BienToanCuc();
            btc.maND = txt_MaPHCu.getText();
            btc.luaChonPH=2;
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_btn_OKActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        lamMoi();
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void txt_HoTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HoTenKeyReleased
        if(Validation.isEmpty(txt_HoTen)){
            lbl_ValidHoTen.setText("Không được trống!");
        }
        else {
                lbl_ValidHoTen.setText(null);
        }
//        System.out.println(setOK());
        
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_HoTenKeyReleased

    private void txt_NamSinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NamSinhKeyReleased
        if(Validation.isEmpty(txt_NamSinh)){
            lbl_ValidNamSinh.setText("Không được trống!");
        }
        else {
           if(Validation.isYear(txt_NamSinh)){
               lbl_ValidNamSinh.setText(null);
           } else{
               lbl_ValidNamSinh.setText("Không đúng định dạng!");
           }
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_NamSinhKeyReleased

    private void txt_DanTocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DanTocKeyReleased
        if(Validation.isEmpty(txt_DanToc)){
            lbl_ValidDanToc.setText("Không được trống!");
        }
        else {
                lbl_ValidDanToc.setText(null);
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_DanTocKeyReleased

    private void txt_CCCDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CCCDKeyReleased
        if(Validation.isEmpty(txt_CCCD)){
            lbl_ValidCCCD.setText("Không được trống!");
        }
        else {
           if(Validation.isCCCD(txt_CCCD)){
               lbl_ValidCCCD.setText(null);
           } else{
               lbl_ValidCCCD.setText("Không đúng định dạng!");
           }
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_CCCDKeyReleased

    private void txt_DiaChiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DiaChiKeyReleased
        if(Validation.isEmpty(txt_DiaChi)){
            lbl_ValidDiaChi.setText("Không được trống!");
        }
        else {
                lbl_ValidDiaChi.setText(null);
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_DiaChiKeyReleased

    private void txt_SDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SDTKeyReleased
        if(Validation.isEmpty(txt_SDT)){
            lbl_ValidSDT.setText("Không được trống!");
        }
        else {
           if(Validation.isPhoneNumber(txt_SDT)){
               lbl_ValidSDT.setText(null);
           } else{
               lbl_ValidSDT.setText("Không đúng định dạng!");
           }
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_SDTKeyReleased

    private void txt_EmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EmailKeyReleased

        if(Validation.isEmpty(txt_Email)){
            lbl_ValidEmail.setText(null);
            txt_Email.setBackground(Color.white);
        }
        else {
           if(Validation.isEmail(txt_Email)){
               lbl_ValidEmail.setText(null);
           } else{
               lbl_ValidEmail.setText("Không đúng định dạng!");
           }
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_EmailKeyReleased

    private void txt_MaPHCuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MaPHCuKeyReleased
        if(Validation.isEmpty(txt_MaPHCu)){
            lbl_ValidMaPH.setText("Không được trống!");
        }
        else {
           if(Validation.isID(txt_MaPHCu, "ph")){
               lbl_ValidMaPH.setText(null);
           } else{
               lbl_ValidMaPH.setText("Không đúng định dạng!");
           }
        }
//        System.out.println(setOK());
        if(checkValidation()){
            btn_OK.setEnabled(true);
        } else{
            btn_OK.setEnabled(false);
        }
    }//GEN-LAST:event_txt_MaPHCuKeyReleased

    private void btn_PHMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PHMoiActionPerformed

//        btn_PHMoi.setSelected(true);
        luaChonPH();
    }//GEN-LAST:event_btn_PHMoiActionPerformed

    private void btn_PHCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PHCuActionPerformed

//        btn_PHCu.setSelected(true);
        luaChonPH();
    }//GEN-LAST:event_btn_PHCuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JF_ThongTinPhuHuynh jf = new JF_ThongTinPhuHuynh();
                jf.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abc;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JRadioButton btn_Nam;
    private javax.swing.JRadioButton btn_Nu;
    private javax.swing.JButton btn_OK;
    private javax.swing.JRadioButton btn_PHCu;
    private javax.swing.JRadioButton btn_PHMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_ValidCCCD;
    private javax.swing.JLabel lbl_ValidDanToc;
    private javax.swing.JLabel lbl_ValidDiaChi;
    private javax.swing.JLabel lbl_ValidEmail;
    private javax.swing.JLabel lbl_ValidHoTen;
    private javax.swing.JLabel lbl_ValidMaPH;
    private javax.swing.JLabel lbl_ValidNamSinh;
    private javax.swing.JLabel lbl_ValidSDT;
    private javax.swing.JTextField txt_CCCD;
    private javax.swing.JTextField txt_DanToc;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_MaPH;
    private javax.swing.JTextField txt_MaPHCu;
    private javax.swing.JTextField txt_NamSinh;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenDN;
    // End of variables declaration//GEN-END:variables
}
