/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.ConnectDB_PhuHuynh;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashSet;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import models.BienToanCuc_QLHS;
import static models.BienToanCuc_QLHS.phuhuynh;
import models.NguoiDung;
public class ThongTinPhuHuynh extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinPhuHuynh
     */
    
    public ThongTinPhuHuynh() {
        initComponents();
        setLocationRelativeTo(null);
        txt_MaPH.setEnabled(false);
        txt_TenDN.setEnabled(false);
        //Lấy list Phụ huynh từ CSDL
        ArrayList<NguoiDung> listPH = new ConnectDB_PhuHuynh().selectQuery();
        btnNam.setSelected(true);
        btnPHMoi.setSelected(true);
        
        int id = 1;
        boolean state;
        while(true){
            state = false;
            for(NguoiDung ph: listPH){
                if(ph.getMaND().equals("ph"+id)){
                    state = true;
                    break;
                }
            }
            if(!state) break;
            ++id;
        }
        txt_MaPH.setText("ph"+ id);
        txt_TenDN.setText(txt_MaPH.getText());
        
        //Load lại thông tin PH vừa điền khi chưa thực hiện nhấn Thêm hoặc Cập Nhật
        //Cho vào try-catch do TH btc null --> Exception
        try{
            HienThiThongTinPH(new BienToanCuc_QLHS());
        }catch(Exception e) {
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //Hàm load lại Thông tin PH lên biểu mẫu
    public void HienThiThongTinPH(BienToanCuc_QLHS btc){
        NguoiDung ph = btc.getPhuhuynh();
        
        if(btc.luaChonPH == 1){
            btnPHMoi.setSelected(true);
            txt_MaPH.setText(ph.getMaND());
            txt_TenDN.setText(ph.getTenDN());
            txt_HoTenPH.setText(ph.getHoTen());
            txt_NamSinhPH.setText(ph.getNamSinh()+"");

            if(ph.isGioiTinh()){
                btnNam.setSelected(true);
            } else {
                btnNu.setSelected(true);
            }

            txt_DanTocPH.setText(ph.getDanToc());
            txt_CCCD.setText(ph.getCccd());
            txt_DiaChi.setText(ph.getDiaChi());
            txt_SDT.setText(ph.getSoDT());
            txt_Email.setText(ph.getEmail());
            
        } else if(btc.luaChonPH==2){
            btnPHCu.setSelected(true);
            
            txtMaPHCu.setText(btc.getMaND());
        }
        
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        abc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_HoTenPH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_NamSinhPH = new javax.swing.JTextField();
        txt_DanTocPH = new javax.swing.JTextField();
        txt_CCCD = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnNam = new javax.swing.JRadioButton();
        btnNu = new javax.swing.JRadioButton();
        btnDong = new javax.swing.JButton();
        btnPHMoi = new javax.swing.JRadioButton();
        btnPHCu = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaPHCu = new javax.swing.JTextField();
        txt_MaPH = new javax.swing.JTextField();
        txt_TenDN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Phụ Huynh");

        abc.setText("Mã phụ huynh:");

        jLabel3.setText("Tên đăng nhập: ");

        jLabel4.setText("Mật khẩu: Khởi tạo ban đầu mặc định giống mã phụ huynh");

        jLabel6.setText("Họ tên");

        txt_HoTenPH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_HoTenPHFocusLost(evt);
            }
        });

        jLabel7.setText("Năm sinh");

        jLabel8.setText("Giới tính");

        jLabel9.setText("Dân tộc");

        jLabel10.setText("CCCD");

        jLabel11.setText("Đạ chỉ");

        jLabel12.setText("Số điện thoại");

        jLabel13.setText("Email");

        txt_NamSinhPH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NamSinhPHFocusLost(evt);
            }
        });

        txt_DanTocPH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DanTocPHFocusLost(evt);
            }
        });

        txt_CCCD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CCCDFocusLost(evt);
            }
        });

        btnOK.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Ok24.png")); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\Refresh.png")); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNam);
        btnNam.setText("Nam");

        buttonGroup1.add(btnNu);
        btnNu.setText("Nữ");

        btnDong.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Hanoi University of Science and Technology\\Desktop\\PJ Java\\BTL_test\\src\\images\\CloseJF24.png")); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnPHMoi);
        btnPHMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPHMoi.setText("Phụ huynh mới");

        buttonGroup2.add(btnPHCu);
        btnPHCu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPHCu.setText("Phụ huynh cũ");

        jLabel2.setText("Mã phụ huynh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnPHCu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPHMoi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaPHCu))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_HoTenPH)
                                    .addComponent(txt_NamSinhPH)
                                    .addComponent(txt_DanTocPH)
                                    .addComponent(txt_CCCD)
                                    .addComponent(txt_DiaChi)
                                    .addComponent(txt_SDT)
                                    .addComponent(txt_Email)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDong)
                                .addGap(18, 18, 18)
                                .addComponent(btnLamMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btnOK))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(abc))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_MaPH)
                                    .addComponent(txt_TenDN))))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnPHMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_TenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_HoTenPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_NamSinhPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnNam)
                    .addComponent(btnNu))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_DanTocPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txt_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPHCu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPHCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnLamMoi)
                    .addComponent(btnDong))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if(btnPHMoi.isSelected()){
            
            NguoiDung ph = new NguoiDung();
        try{
            ph.setMaND(txt_MaPH.getText());
            ph.setHoTen(txt_HoTenPH.getText());
            ph.setDanToc(txt_DanTocPH.getText());
            ph.setTenDN(txt_MaPH.getText());
            ph.setCccd(txt_CCCD.getText());
            ph.setDiaChi(txt_DiaChi.getText());
            ph.setSoDT(txt_SDT.getText());
            ph.setEmail(txt_Email.getText());
            ph.setMatKhau(txt_MaPH.getText());

             //set giới tính
            if(btnNam.isSelected()){
               ph.setGioiTinh(true);
            } else if(btnNu.isSelected()){
                ph.setGioiTinh(false);
            }

            ph.setNamSinh(Integer.parseInt(txt_NamSinhPH.getText()));
            ph.setVaiTro("phuhuynh");
            
            BienToanCuc_QLHS btc = new BienToanCuc_QLHS();
            btc.setPhuhuynh(ph);
            btc.setLuaChonPH(1);
            
            this.dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu trống hoặc không đúng định dạng, vui lòng kiểm tra lại!");
            }
        } else if(btnPHCu.isSelected()){
            
            BienToanCuc_QLHS btc = new BienToanCuc_QLHS();
            btc.setMaND(txtMaPHCu.getText());
            btc.setLuaChonPH(2);
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txt_HoTenPH.setText("");
        txt_NamSinhPH.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        txt_DanTocPH.setText("");
        txt_CCCD.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        txt_Email.setText("");
        
        btnNam.setSelected(true);
        btnPHMoi.setSelected(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txt_NamSinhPHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NamSinhPHFocusLost
        if(this.isVisible()){
            String str = txt_NamSinhPH.getText();
            String dinhDang = "^(([12][0-9][0-9][0-9]))$";

            if(str.length()>0){
                if(! str.matches(dinhDang)){
                    JOptionPane.showMessageDialog(rootPane, "Sai định năm sinh!");
                    txt_NamSinhPH.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ngày sinh không được để trống!");
                txt_NamSinhPH.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_NamSinhPHFocusLost

    private void txt_HoTenPHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_HoTenPHFocusLost
        if(this.isVisible()){
            String str = txt_HoTenPH.getText();
            if(!(str.length()>0)){
                JOptionPane.showMessageDialog(rootPane, "Họ tên không được để trống!");
                txt_HoTenPH.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_HoTenPHFocusLost

    private void txt_DanTocPHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DanTocPHFocusLost
        if(this.isVisible()){
            String str = txt_NamSinhPH.getText();
            if(!(str.length()>0)){
                JOptionPane.showMessageDialog(rootPane, "Năm sinh không được để trống!");
                txt_NamSinhPH.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_DanTocPHFocusLost

    private void txt_CCCDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CCCDFocusLost
        if(this.isVisible()){
            String str = txt_CCCD.getText();
            String dinhDang = "^\\d{1,13}$";

            if(str.length()>0){
                if(! str.matches(dinhDang)){
                    JOptionPane.showMessageDialog(rootPane, "Sai định dạng ngày!");
                    txt_CCCD.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ngày sinh không được để trống!");
                txt_CCCD.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_CCCDFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinPhuHuynh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinPhuHuynh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abc;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JButton btnOK;
    private javax.swing.JRadioButton btnPHCu;
    private javax.swing.JRadioButton btnPHMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtMaPHCu;
    private javax.swing.JTextField txt_CCCD;
    private javax.swing.JTextField txt_DanTocPH;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_HoTenPH;
    private javax.swing.JTextField txt_MaPH;
    private javax.swing.JTextField txt_NamSinhPH;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenDN;
    // End of variables declaration//GEN-END:variables
}
